- name: Itinerario El Cabanyal
  image: /assets/images/Itinerarios/Itinerario-Histórico-por-El-Cabanyal_thumbnail.png
  link: /blog/Itinerario-Histórico-por-El-Cabanyal
  description: Paseo histórico por un barrio de Valencia 
  
- name: Itinerario Botánico
  link: /blog/Itinerario-Botánico
  image: /assets/images/Itinerarios/Itinerario-Botánico_thumbnail.png
  description: Una vuelta por el Botánico de Valencia
  
- name: Les Rodanes Actividades
  link: /blog/Les-Rodanes-Actividades
  image: /assets/images/Itinerarios/Les-Rodanes-Actividades_thumbnail.png
  description: Actividades en marcha por la naturaleza
  
- name: Perfil de Ruta Cheste
  link: /blog/Mapa-y-Perfil-Ruta-Peñaroya-Cheste
  image: /assets/images/Itinerarios/Mapa-y-Perfil-Ruta-Peñaroya-Cheste_thumbnail.png
  description: Perfil de un itinerario a analizar


  
